### ISSUE TITLE
Audio files

### ISSUE THREAD

**Issue by arkhodamoradi** [h-betz/NeuralNetwork#1]
Hello,

which audio files correspond to audio and audio2:
https://github.com/h-betz/NeuralNetwork/blob/master/SNN.py#L162

**Comment by h-betz** [comment]
@arkhodamoradi So I actually had to purchase this data - it can be found here https://catalog.ldc.upenn.edu/LDC2008S07

I can't explicitly share the data due to a binding agreement but you can get it from this resource.

**Comment by arkhodamoradi** [comment]
thank you
